# Generated by Django 4.1.7 on 2023-05-18 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(default='store/images/default.png', upload_to='artshop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('image', models.ImageField(default='store/images/default.png', upload_to='store/images')),
                ('price', models.FloatField(default=0.0)),
                ('public_day', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='artshop.category')),
            ],
        ),
    ]
