# Generated by Django 4.1.7 on 2023-05-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='public_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='viewed',
        ),
    ]
