# Generated by Django 4.1.7 on 2023-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
